/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mumtaz.salary.view;

import com.mumtaz.salary.db.Koneksi;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author erdiansyah
 */
public class ViewListDataPinjaman extends javax.swing.JFrame {

    /**
     * Creates new form ViewListDataPinjaman
     */
    private ViewPinjaman VP;
    private DefaultTableModel model;
    private String sql = "";
    public ViewListDataPinjaman(ViewPinjaman VP) {
        initComponents();
        this.VP = VP;
        model = new DefaultTableModel();
        tabelPegawai.setModel(model);
        model.addColumn("ID Pegawai");
        model.addColumn("Nama Pegawai");
        model.addColumn("Jabatan");
        model.addColumn("Pinjaman");
        tampilPegawai("");
    }
    private void tampilPegawai(String data){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        if(data.equals("")){
            sql = "SELECT idPegawai, namaPegawai, jabatan, kasbon FROM pegawai";
        } else sql = "SELECT idPegawai, namaPegawai, jabatan, kasbon FROM pegawai WHERE namaPegawai LIKE '"+data+"%'";
        
        try {
            Statement stat = (Statement) Koneksi.getKoneksi().createStatement();
            ResultSet result = stat.executeQuery(sql);
            while(result.next()){
                Object[] hasil;
                hasil = new Object[4];
                hasil[0] = result.getString("idPegawai");
                hasil[1] = result.getString("namaPegawai");
                hasil[2] = result.getString("jabatan");
                hasil[3] = result.getString("kasbon");
                
                model.addRow(hasil);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ViewListDataPinjaman.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPegawai = new javax.swing.JTable();
        namaPegawai = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabelPegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPegawaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPegawai);

        namaPegawai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namaPegawai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                namaPegawaiKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cari Nama Pegawai");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(namaPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPegawaiMouseClicked
        // TODO add your handling code here:
        int listX = tabelPegawai.getSelectedRow();
        VP.getIdPegawai().setText(tabelPegawai.getValueAt(listX, 0).toString());
        VP.getNamaPegawai().setText(tabelPegawai.getValueAt(listX, 1).toString());
        VP.getJabatan().setText(tabelPegawai.getValueAt(listX, 2).toString());
        VP.getTotalKasbon().setText(tabelPegawai.getValueAt(listX, 3).toString());
        dispose();
    }//GEN-LAST:event_tabelPegawaiMouseClicked

    private void namaPegawaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaPegawaiKeyPressed
        // TODO add your handling code here:
        tampilPegawai(namaPegawai.getText());
    }//GEN-LAST:event_namaPegawaiKeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField namaPegawai;
    private javax.swing.JTable tabelPegawai;
    // End of variables declaration//GEN-END:variables
}
